name: "ğŸ Bug Report (Developers Only)"
description: "ğŸš« For developers only. End-users please use Discussions for support."
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # âœ‹ğŸ›‘ STOP â€” READ THIS FIRST

        This **Bug Report form is for the Code for Recovery TSML team only**.

        ğŸ‘‰ Please **[Create a Discussion](https://github.com/code4recovery/12-step-meeting-list/discussions/new?category=q-a)** to get help from our support rotation.  